[package]
name = "vitess-grpc-shared"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
vitess-grpc = { path = "vitess-grpc" }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"

[workspace]
members = [
  "vitess-grpc",
  "vitess-grpc-test",
]
